### ISSUE TITLE
Some plugins are "abandoned" (but I fixed them). Could I integrate them as channels?

### ISSUE THREAD

**Issue by diegorodriguezv** [blissland/blissflixx#58]
Hi.
Some of the plugins seem to be abandoned by their creators. I think they can still be useful to blissflixx users so I fixed them. They are hosted here:
https://github.com/diegorodriguezv/bfch_eztv
https://github.com/diegorodriguezv/bfch_kickass_torrents
https://github.com/diegorodriguezv/bfch_yts_torrents
https://github.com/diegorodriguezv/bfch_pirate_bay
https://github.com/diegorodriguezv/bfch_xnxx
Is it a good idea to merge them into the blissflixx code as channels?

**Comment by diegorodriguezv** [comment]
Id like to post messages in the forums (http://forum.blissflixx.rocks) pointing to the updated channels so people can find out about them but my account (diegorodriguezv) appears to be banned because of spam. Could I be unbanned? I'm sure I have never posted anything...

**Comment by blissland** [comment]
OK I  have unbanned you. The reason was that the forum was getting flooded with spam users so I had to do mass banning of accounts and sometimes accidentally banned users, like yourself, which were not spam accounts. Also feel free to merge your channels into the main code. Thanks again for your work on this!
